### PR TITLE
Cisco

### PR DESCRIPTION
**Pull request by nickbalestra**

### CODE REVIEW

**Comment by nickbalestra** [comment]
If you read Cisco page for logo usage, is not allowed to use any logo without excplicit consensus, therefore they have a logo request portal. In the meanwhile I'll suggest we do like this and then we apply for the logo

**Comment by nickbalestra** [comment]
For linking to actual site using OC, I think we should then do it for each project and in the future that could be harder and take more time to check, I'll suggest that when we'll expand more with testimonial and info section in there you'll find link to project used (if any), ecc. This will allow for a standard way to handle adapters page.

**Comment by nickbalestra** [comment]
@BhautikDoshi what you think? Is there anyway you could help us with this perhaps?

**Comment by matteofigus** [comment]
Ok I think you're right! Let's see if Bhautik replies, perhaps we can help us clarifying this :)

**Comment by BhautikDoshi** [comment]
@matteofigus @nickbalestra, sure happy to help.
Let me know if you already initiated the request and I need to endorse on it or I should initiate one.

**Comment by nickbalestra** [comment]
@BhautikDoshi haven't initiated one yet, if you could initiate one, that will be awesome, thanks!
Let me know in case you need anything on our side

**Comment by BhautikDoshi** [comment]
@nickbalestra  I have submitted the request. Once approved, I will update here.

**Comment by matteofigus** [comment]
Any news about that @BhautikDoshi ? Thanks

**Pull request closed without merging**
