### PR TITLE
review

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- readme

- h1 bad font family

- typos

- meta tag for mobile devices

- GoogleAnalyticsObject

- package.json

## Todos

- [x] create GoogleAnalyticsObject tracking ID

- [ ] https://opencomponents.now.sh/ doesn't look quite right to me

### CODE REVIEW

**Comment by nickbalestra** [comment]
Thanks for this Mattia, awesome work!
for the point 2, I did some investigation and opened an issue [here](https://github.com/opencomponents/get-started/issues/2)

I'm going to merge and publish your change then.

**Comment by nickbalestra** [comment]
@mattiaerre only one small thing, can you bump the version of the landing-page component?

**Comment by mattiaerre** [comment]
@nickbalestra done!

**Comment by matteofigus** [comment]
@nickbalestra can you take care of publishing? (or, is it automatically done by travis?)

**Comment by nickbalestra** [comment]
I'll do it

**Pull request merged**
